//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Controllers
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public int ID { get; set; }
        public string Comida { get; set; }
        public string Descrição { get; set; }
        public string Categoria { get; set; }
        public string Origem { get; set; }
        public string Ingredientes { get; set; }
        public string Aonde_comer { get; set; }
        public string Preparo { get; set; }
        public string Melhor_Chef { get; set; }
        public string Preço { get; set; }
    }
}
