//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class FILME
    {
        public decimal COD_FILME { get; set; }
        public string FILME1 { get; set; }
        public decimal COD_CATEGORIA { get; set; }
        public string DIRETOR { get; set; }
        public double VALOR_LOCACAO { get; set; }
        public string RESERVADA { get; set; }
    }
}
